repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: check-yaml
        stages: [pre-commit, pre-push, manual]
    -   id: check-json
        stages: [pre-commit, pre-push, manual]
    -   id: end-of-file-fixer
        stages: [pre-commit, pre-push, manual]
    -   id: trailing-whitespace
        stages: [pre-commit, pre-push, manual]
        exclude: README.md
-   repo: local
    hooks:
    # isort - sorts and formarts python imports
    -   id: isort
        name: isort
        entry: isort --profile black
        language: system
        types: [python]
        stages: [pre-commit, pre-push]
    # black -  Python code formatter
    -   id: black
        name: black
        entry: black
        language: system
        types: [python]
        stages: [pre-commit, pre-push]
    # flake8 - checks Python code for style and syntax errors
    -   id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [python]
        stages: [pre-commit, pre-push]

    # mypy - static type checker for Python code
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.10.0'
    hooks:
    -   id: mypy
        language: system
        types: [python]
        stages: [pre-commit, pre-push]
